name: EnhancedSpawners
version: 1.3.0
description: A plugin which enhances spawners in various ways
author: austinv11
website: austinv11.github.io
 
main: io.github.austinv11.EnhancedSpawners.EnhancedSpawners
commands:
   set-delay:
      description: Sets the delay of the spawner you are looking at
      usage: /<command> <delay>
      permission: EnhancedSpawners.set-delay
      permission-message: You don't have permission
      aliases: [setdelay, delay-set, delayset]
   set-mob:
      description: Sets mob of the spawner you are looking at
      usage: /<command> <mob> <optional:delay>
      permission: EnhancedSpawners.set-mob
      permission-message: You don't have permission
      aliases: [setmob, mob-set, mobset]
   new-spawner:
      description: Creates a mob spawner where you are looking at
      usage: /<command> <mob> <optional:delay>
      permission: EnhancedSpawners.new-spawner
      permission-message: You don't have permission
      aliases: [newspawner, make-spawner, makespawner]
   give-spawner:
      description: Gives you either the spawner you are looking at, or the one you input
      usage: /<command> <mob> <optional:player> or /<command>
      permission: EnhancedSpawners.give-spawner
      permission-message: You don't have permission
      aliases: [givespawner, get-spawner, getspawner]
   spawner-finder:
      description: Gives you or a specified player a Spawner Finder
      usage: /<command> <optional:player>
      permission: EnhancedSpawners.spawner-finder
      permission-message: You don't have permission
      aliases: [spawnerfinder, find-spawner, findspawner]

permissions:
   EnhancedSpawners.*:
        description: Gives access to all EnhancedSpawners commands
   EnhancedSpawners.set-delay:
      description: Sets the delay of the spawner you are looking at
   EnhancedSpawners.set-mob:
      description: Sets mob of the spawner you are looking at
   EnhancedSpawners.silkySpawners:
      description: Allows for silk touching spawners
      default: true
   EnhancedSpawners.new-spawner:
      description: Creates a mob spawner where you are looking at
   EnhancedSpawners.give-spawner:
      description: Gives you either the spawner you’re looking at, or the one you input
   EnhancedSpawners.spawner-finder:
      description: Gives you or a specified player a Spawner Finder