name: EnhancedSpawners
version: 1.0.0-SNAPSHOT
description: A plugin which enhances spawners in various ways
author: austinv11
website: austinv11.github.io
 
main: io.github.austinv11.EnhancedSpawners.EnhancedSpawners
commands:
   spawner-list:
      description: Displays all the possible entities for spawners
      usage: /<command>
      permission: EnhancedSpawners.spawner-list
      permission-message: You don't have permission
      aliases: [spawnerlist, spawn-list, spawnlist]

permissions:
   EnhancedSpawners.*:
        description: Gives access to all LootPlus commands
        children:
            EnhancedSpawners.spawner-list: true
   EnhancedSpawners.spawner-list:
      description: Displays the tweaks implemented by LootPlus on the server
      default: true