name: EnhancedSpawners
version: 1.1.0
description: A plugin which enhances spawners in various ways
author: austinv11
website: austinv11.github.io
 
main: io.github.austinv11.EnhancedSpawners.EnhancedSpawners
commands:
   set-delay:
      description: Sets the delay of the spawner you are looking at
      usage: /<command> <delay (number)>
      permission: EnhancedSpawners.set-delay
      permission-message: You don't have permission
      aliases: [setdelay, delay-set, delayset]
   set-mob:
      description: Sets mob of the spawner you are looking at
      usage: /<command> <mob>
      permission: EnhancedSpawners.set-delay
      permission-message: You don't have permission
      aliases: [setmob, mob-set, mobset]

permissions:
   EnhancedSpawners.*:
        description: Gives access to all LootPlus commands
   EnhancedSpawners.set-delay:
      description: Sets the delay of the spawner you are looking at
   EnhancedSpawners.set-mob:
      description: Sets mob of the spawner you are looking at
   EnhancedSpawners.silkySpawners:
      description: Allows for silk touching spawners
      default: true